//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomad.Plugins.HelloDevicePlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nomad.Plugins.HelloDevicePlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время отправки письма администратору произошла ошибка.
        /// </summary>
        internal static string AdminEmailError {
            get {
                return ResourceManager.GetString("AdminEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь &quot;{0}&quot; подключил новое устройство &quot;{1}&quot;.
        /// </summary>
        internal static string AdminEmailSubject {
            get {
                return ResourceManager.GetString("AdminEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компиляция шаблона: {0}.
        /// </summary>
        internal static string CompileTemplateTrace {
            get {
                return ResourceManager.GetString("CompileTemplateTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось отправить email-сообщение. Получатель: {0}.
        /// </summary>
        internal static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправка сообщения &quot;{1}&quot; для {0}.
        /// </summary>
        internal static string EmailTrace {
            get {
                return ResourceManager.GetString("EmailTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка инициализации плагина.
        /// </summary>
        internal static string InitializationError {
            get {
                return ResourceManager.GetString("InitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инициализация плагина HelloDevicePlugin.
        /// </summary>
        internal static string InitializationTrace {
            get {
                return ResourceManager.GetString("InitializationTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIRECTUM.
        /// </summary>
        internal static string SystemName {
            get {
                return ResourceManager.GetString("SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь к папке шаблонов email-сообщений: {0}.
        /// </summary>
        internal static string TemplatesPathTrace {
            get {
                return ResourceManager.GetString("TemplatesPathTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время отправки письма пользователю произошла ошибка.
        /// </summary>
        internal static string UserEmailError {
            get {
                return ResourceManager.GetString("UserEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключено новое устройство: &quot;{0}&quot;.
        /// </summary>
        internal static string UserEmailSubject {
            get {
                return ResourceManager.GetString("UserEmailSubject", resourceCulture);
            }
        }
    }
}
